repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path, pyproject.toml]
        files: ./src

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--config, pyproject.toml]
        files: ./src

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--config, .flake8]
        files: ./src

  - repo: local
    hooks:
      - id: mypy
        name: local mypy
        entry: make check-static-type
        files: ./app
        language: python

  - repo: local
    hooks:
      - id: pytest
        name: local pytest
        entry: make test
        files: ./tests
        language: python
