name: "Pentium Network: Send pull request to modify Mavis Helmfile"
description: "Auto send Pull Request to Mavis branch"

branding:
  icon: "info"
  color: "green"

inputs:
  target_repo:
    required: true
    description: "Specify which micro service app version is going to be modified."
  target_repo_app_version:
    required: true
    description: "Specify which micro service app version is going to be modified."
  head:
    required: true
    description: "Head branch name"
  base:
    required: true
    description: "Base branch name"
  action_name:
    required: false
    description: Subcommand of github action. Currently support mavis-helm-update-action only.
    default: mavis-helm-update-action
  sub_action_name:
    required: false
    description: Subcommand of github action. Currently support mavis-helm-update-action only.
    default: pull-request
  pr_to:
    required: false
    description: Subcommand of github action. Currently support mavis-helm-update-action only.
    default: mavis

# outputs:

runs:
  using: "docker"
  image: "Dockerfile"
  args:
      - 
  #   - ${{ inputs.action_name }}
  #   - ${{ inputs.sub_action_name }}
  #   - ${{ inputs.head }}
  #   - ${{ inputs.base }}
  #   - ${{ inputs.target_repo }}
  #   - ${{ inputs.target_repo_app_version }}
  #   - --pr_to=${{ inputs.pr_to }}
