on:
  push:
    branches:
      - "mavis-1743-dev-gh-action-e2e"
      - "test-release"
      - "*"

jobs:
  get-tag:
    runs-on: general
    container:
      image: cr-preview.pentium.network/basic-action:1.0.0
    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
    steps:
      - name: Get tag
        id: tag
          # echo "TAG=${GITHUB_RUN_NUMBER}-$(echo ${GITHUB_SHA}| cut -c 1-3)"  >> $GITHUB_OUTPUT
        run: |
          echo "TAG=${GITHUB_RUN_NUMBER}"  >> $GITHUB_OUTPUT

  release-on-github:
    needs: get-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "dev-release-${{  needs.get-tag.outputs.tag }}"
          tag_exists_error: false
          message: "Release for e2e test for ${{  needs.get-tag.outputs.tag }}"
          github_token: ${{ secrets.SECRET_KEY }}
          force_push_tag: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_KEY }}
          # GITHUB_TOKEN: ${{ secrets.DEV_GITHUB_ACCESS_TOKEN }}
        with:
          tag_name: "dev-release-${{  needs.get-tag.outputs.tag }}"
          release_name: "Release dev-release-${{  needs.get-tag.outputs.tag }}"
          body: |
            Release dev-release-${{  needs.get-tag.outputs.tag }}
          draft: false
          prerelease: false
